# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
# devices([
#   "iPhone 6",
#   "iPhone 6 Plus",
#   "iPhone 5",
#   "iPad Pro (12.9-inch)",
#   "iPad Pro (9.7-inch)",
#   "Apple TV 1080p"
# ])

# devices([
#   "iPhone 5s",
#   "iPhone 6",
#   "iPhone 6 Plus",
#   "iPhone 6s",
#   "iPhone 6s Plus",
#   "iPhone 7",
#   "iPhone 7 Plus",
#   "iPhone 8",
#   "iPhone 8 Plus",
#   "iPhone X",
#   "iPhone SE",
#   "iPad Air",
#   "iPad Air 2",
#   "iPad (5th generation)",
#   "iPad Pro (9.7-inch)",
#   "iPad Pro (10.5-inch)",
#   "iPad Pro (12.9-inch)",
#   "iPad Pro (12.9-inch) (2nd generation)"
# ])

# devices([
#   "iPhone 5s",
#   "iPhone 6",
#   "iPhone 6 Plus",
#   "iPhone 6s",
#   "iPhone 6s Plus",
#   "iPhone 7",
#   "iPhone 7 Plus",
#   "iPhone 8",
#   "iPhone 8 Plus",
#   "iPhone X",
#   "iPhone SE"
# ])

devices([
  "iPhone SE",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone X"
])

# devices([
#   "iPad Pro (12.9-inch) (2nd generation)"
# ])

# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
# ])

languages([
  "en-US"
])

# languages([
#   "en-US",
#   "de-DE",
#   "ru-RU",
#   "es-ES",
#   "fr-FR"
# ])

# The name of the scheme which contains the UI Tests
scheme("DVUITests")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# xargs arent passing... maybe we need to reinstall
# reinstall_app true
# stop if there is an error
stop_after_first_error true
# clean up old stuff... what's the point... I am updating
clear_previous_screenshots true
# flag used to call various stuff in the code using if SCREENSHOTS
# xcargs("--xcargs GCC_PREPROCESSOR_DEFINITIONS='SCREENSHOTS'")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots true

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
